### ISSUE TITLE
Dates are missing when fast switching

### ISSUE THREAD

**Issue by valthec** [chemerisuk/better-dateinput-polyfill#47] opened 2015-05-24 11:50 UTC
When you click fast on left or right arrows, bottom panel with dates may disappear and stay hidden until you reload whole page. I was able to replicate this issue on Internet Explorer 11 and Firefox 38. 
![2015-05-24_134246](https://cloud.githubusercontent.com/assets/12583808/7787730/79e61cca-021b-11e5-9696-abf0d24447a6.png)
![2015-05-24_134234](https://cloud.githubusercontent.com/assets/12583808/7787732/7c097722-021b-11e5-8304-a1a977ab103e.png)

**Comment by chemerisuk** [comment] 2015-05-24 13:28
@valthec there is such a bug indeed. I believe it will be fixed on better-dom side when version 3 will be released. In short the cause is using `requestAnimationFrame` for visibility methods in better-dom.

**Comment by dlsso** [comment] 2015-10-02 17:52
Seems like switching month shouldn't be based on animation frame. Some more details in case they are helpful:

It's the first click that matters. If you wait for half a second after the first click you can click as fast as you want without breaking it. Otherwise the 3rd click will hide the days.

**Closed** 2016-04-07 13:38 UTC
Labels: bug
