### ISSUE TITLE
Day that is shown is one off. 

### ISSUE THREAD

**Issue by tomhicz** [chemerisuk/better-dateinput-polyfill#79] opened 2016-05-23 13:05 UTC
I've had reports from a website that I used the polyfill on that the Day is shown as being the wrong day by one. 
Eg, if the 23rd is actually a Monday then the day is shown as a Sunday. (Or possibly a Tuesday, I'm waiting on more information).

**Comment by antoineleclair** [comment] 2016-06-03 14:38
I have the same issue.

The problem seems to be coming from the `is="local-time"` of the underlying `<time>` element.

For example, I'm in Eastern Time (GTM-04:00), so a UTC datetime of 2016-01-01 is converted to 2015-12-31 20:00:00, which shows up as 2015-12-31.

https://github.com/chemerisuk/better-dateinput-polyfill/blob/9166798784ae63dc9628fc11b4d8f190918e662f/src/main.js#L12

I'm not sure what the solution is.

**Comment by antoineleclair** [comment] 2016-06-03 15:42
For now, I added a work around that looks like that

```javascript
function datePolyfillTimezoneFix() {
  $('time.btr-dateinput-value').each(function() {
    var val = moment.utc($(this).next('input').val())
      .utc().format('YYYY-MM-DDTHH:mm:ss');
    DOM.constructor(this).set('datetime', val);
  });
}

$('#input1, #input2').change(datePolyfillTimezoneFix).change();
```

**Comment by tomhicz** [comment] 2016-06-10 02:50
Seems like the issue might have been identified, but I've uploaded a screenshot to illustrate the issue more clearly anyway: 
![date-one-off](https://cloud.githubusercontent.com/assets/999194/15953007/fcf6e596-2f00-11e6-8076-5b60db76fdbd.png)
As you can see, the text in the box shows the correct day/date of Thur 26th may, but the pop-up calendar shows Thursday as being the 27th may. 

I don't have any issues on my timezone, afaik, but the client has issues on their timezone.

**Comment by tomhicz** [comment] 2016-07-14 04:58
What are the odds of this getting fixed in the main code in the next couple of weeks? 
I can try the workaround posted above, but since I have no easy way of checking if it works (as there are no issues in my timezone) I'd prefer an official fix.

**Comment by chemerisuk** [comment] 2016-07-14 12:26
@tomhicz sorry for a long reply. Just to make sure, which version do you use? Is it the latest one? I remember making fixes for the similar case in the past.

**Comment by antoineleclair** [comment] 2016-07-14 12:39
I'm using 2.0.0.

**Comment by chemerisuk** [comment] 2016-07-15 10:52
@antoineleclair I've switched to GTM-04:00 locally, and can't reproduce the issue. The fix was done in https://github.com/chemerisuk/better-dateinput-polyfill/issues/72. Please make sure you have the latest version 2 (not rc).

**Comment by antoineleclair** [comment] 2016-07-15 15:13
@chemerisuk You're totally right. I removed the workaround I had and it seems to work fine. I must have been using an old version on June 3rd, when I left my first comment.

@tomhicz Can you confirm the issue is gone in 2.0.0?

**Comment by tomhicz** [comment] 2016-08-11 13:21
Sorry to take a while to get back to you, I was focussed on other projects. 

Just to confirm that it seems to work fine on the release version. I'm not quite sure why I was on the rc version... either just bad timing just before release or the bower version or instructions not having been updated at the time of download. 

Thanks for all the hard work!

**Comment by chemerisuk** [comment] 2016-08-11 13:51
Alright, closing the issue then. Thanks everybody.

**Closed by chemerisuk** 2016-08-11 13:51 UTC
