### ISSUE TITLE
Calendar panel vanishes when changing month quickly

### ISSUE THREAD

**Issue by cstorey** [chemerisuk/better-dateinput-polyfill#56] opened 2015-10-19 09:45 UTC
There basically seems to be a race condition in the post-transition handler in https://github.com/chemerisuk/better-dateinput-polyfill/blob/08b15d52ecf7b1654ef60e1bac63295137174262/src/main.js#L133 . So, because the code ends up re-using the same two chunks of dom, swapping them each time you switch month, it's possible to end up with an event sequence roughly like:

```
Hide calenderDays[0] (with remove on finish)
Hide calenderDays[1] (with remove on finish)
(transitions occur)
Remove calenderDays[0]
Remove calenderDays[1]
```

**Comment by chemerisuk** [comment] 2015-10-23 22:27
Is it a duplicate of https://github.com/chemerisuk/better-dateinput-polyfill/issues/47?

**Closed** 2016-03-13 07:34 UTC
