### ISSUE TITLE
Changing date with javascript / jQuery

### ISSUE THREAD

**Issue by AlexDubstone** [chemerisuk/better-dateinput-polyfill#80] opened 2016-05-23 21:55 UTC
Hey Maksim,

I'm using version 2.0.0 and am trying to build a range picker with two date inputs. I can change the value of the second input, but unfortunately is does not get shown. Is there any documentation or example on how to change the date correctly?

Regards
Alex

**Comment by chemerisuk** [comment] 2016-05-24 07:25
@AlexDubstone try to trigger the `change` event to update visible value.

**Comment by AlexDubstone** [comment] 2016-05-24 10:03
I created a Plunkr to show what I am doing. If I change the value to '2014-01-01' the datepicker starts in 2014 but it is not visible in the input field.

http://plnkr.co/edit/Y2DKmiTst4jwTEdMt8gX?p=preview

**Comment by chemerisuk** [comment] 2016-05-25 12:14
@AlexDubstone okay, I got it now.

The problem is that jQuery uses it's own internal event system, unlike better-dom that just provides syntax sugar on browser's events. Therefore we can't use jQuery to trigger `"change"` event. Instead you can use code like below:

```js
DOM.constructor($('#dateFrom')[0]).fire("change");
```  

This line gets `$Element` wrapper for a vanilla DOM element and triggers native event for the document. I'll probably take a look at jQuery's source code deeper to investigate if this can be done simple.

Problem 2 from your demo is definetely a edge case that I need to look at as well.

**Comment by AlexDubstone** [comment] 2016-05-25 14:47
Oh I see. Thank you a lot for the explanation why it didn't work the way I tried. :+1:  This solves the issue.

**Comment by chemerisuk** [comment] 2018-06-08 13:27
Should be fixed in version 3

**Closed by chemerisuk** 2018-06-08 13:27 UTC
